// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login-new': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login-new.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/register-new': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register-new.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
    }
    '/api/debug/database': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug/database.get').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.post').default>>>>
    }
    '/api/wows/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wows/create.post').default>>>>
    }
    '/api/wows': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wows/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@22.15.33_db0@0.3.2_sqlite3@5.1.7__encoding@0.1._75g2ekzuhkgmgkdk4mug73qcs4/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}