// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/6/26 下午7:08:26
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/plugins/**/*.{js,ts,mjs}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/composables/**/*.{js,ts,mjs}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/utils/**/*.{js,ts,mjs}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/aotter/Documents/hobby/ooad-ai/apps/aotter-wow-system/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;